/////////////////////////////////////////////////////////////
// cxr_test.h
//
// This file was generated by CXR, the literal string encryptor.
// CXR, Copyright 2002, Smaller Animals Software, Inc., all rights reserved.
//
// Please do not edit this file. Any changes here will be overwritten on the next compile.
// If you wish to make changes to a string, please edit:
//     test.cxr
//

/////////////////////////////////////////////////////////////

#pragma once
#include "cxr_inc.h"

// cxr 적용 테스트입니당

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST1 	_CXR("\x8b\x8e\x81\x89\x82\x8a\x87\x80\x8c\x88\x82\x88\x87\x86\x89\x89\x8a\x8d\x86\x8b\x8e\x84\x8e\x85\x8b\x83\x89\x81\x84\x89\x88\x81\x8c\x87\x87\x83\x83\x86\x83\x83\x80\x89\x84\x8d\x8f\x80\x83\x85\x81\x8c\x86\x83\x85\x83\x85\x80\x8a\x84\x86\x8c\x87\x80\x8b\x86\x88\x8b")
#else
#define STR_CXRTEST1 _CXR("Your all bases are belong to us.")
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST2 	_CXR("\x8c\x8b\x84\x8b\x87\x86\x80\x87\x81\x8c\x83\x83\x88\x87\x87\x8f\x85\x8a\x8e\x8a")// 디파인 뒤에 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST2 _CXR("It's You!")// 디파인 뒤에 주석이 달린 경우를 테스트
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST3 	_CXR("\x8c\x89\x80\x82\x8e\x8d\x8b\x86\x84\x8e")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST3 _CXR("Aye.")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#endif


